# 0 is too far from ` ;)
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g allow-rename off
set-option -g set-titles on

set -g default-terminal screen-256color
set -g status-keys vi
set -g history-limit 10000


setw -g mode-keys vi
setw -g monitor-activity on
set -g status-interval 1

# No delay for escape key press
set -sg escape-time 0

unbind-key C-b
set-option -g prefix C-a
set-environment -g CHERE_INVOKING 1

# send the prefix to client inside window
bind-key C-a send-prefix

# toggle last window like screen
bind-key C-a last-window

# Vim style pane selection
bind-key h select-pane -L
bind-key j select-pane -D 
bind-key k select-pane -U
bind-key l select-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# alternatively, use better mnemonics for horizontal/vertical splits
bind-key - split-window -v
bind-key _ split-window -v
bind-key | split-window -h

bind r source-file ~/.tmux.conf

#################
##### THEME #####
#################
set-option -wg window-status-separator ""

# change window screen colors
set-option -wg mode-style bg="#FE8019",fg="#3C3836"

# default statusbar colors (terminal bg should be #282828)
set-option -g status-style bg="#282828",fg="#A89984"

# default window title colors
set-option -wg window-status-style bg="#282828",fg="#7C6F64"

# colors for windows with activity
set-option -wg window-status-activity-style bg="#282828",fg="#A89984"

# colors for windows with bells
set-option -wg window-status-bell-style bg="#282828",fg="#FE8019"

# active window title colors
set-option -wg window-status-current-style bg="#282828",fg="#b8bb26"

# pane border
set-option -g pane-active-border-style fg="#FE8019"
set-option -g pane-border-style fg="#3C3836"

# message info
set-option -g message-style bg="#FE8019",fg="#3C3836"

# writing commands inactive
set-option -g message-command-style bg="#A89984",fg="#3C3836"

# pane number display
set-option -g display-panes-active-colour "#FE8019"
set-option -g display-panes-colour "#3C3836"

# clock
set-option -wg clock-mode-colour "#FE8019"

# statusbar formatting
set-option -g status-left-length 100
#set-option -g status-left "#[bg=#A89984, fg=#3C3836]#{?client_prefix,#[bg=#fe8019],#[bg=#A89984]} #{session_name} #[bg=#3C3836, fg=#458588] #{window_name} #[fg=#d3869b,bg=#282828] #(whoami)  "
#set-option -g status-right "#[bg=#3C3836, fg=#7C6F64] %Y-%m-%d %H:%M:%S #[bg=#A89984, fg=#3C3836]#{?client_prefix,#[bg=#fe8019],#[bg=#A89984]} #{host_short} "

set-option -g status-left "#[bg=#458588, fg=#32302f]#{?client_prefix,#[bg=#fe8019],#[bg=#458588]} #{session_name} #[bg=#3C3836, fg=#458588]#{?client_prefix,#[fg=#fe8019],#[fg=#458588]} #{window_name} #[fg=#3C3836,bg=#282828]#[fg=#d3869b,bg=#282828] #(whoami) ➤    "
set-option -g status-right "#[bg=#262626, fg=#3C3836]#[bg=#3c3836, fg=#7C6F64] %Y-%m-%d %H:%M:%S #[bg=#3C3836, fg=#3C3836]#{?client_prefix,#[fg=#fe8019],#[fg=#d3869b]}#[bg=#d3869b, fg=#3C3836]#{?client_prefix,#[bg=#fe8019],#[bg=#d3869b]} #{host_short} "

set-option -wg window-status-current-format " #{window_index}  #{window_name} "
set-option -wg window-status-format " #{window_index}  #{window_name} "
